services:
  bosscar-ppf:
    build:
      context: .
      args:
        NEXT_PUBLIC_POCKETBASE_URL: https://dbppf.bosscar.app
    environment:
      - NEXT_PUBLIC_POCKETBASE_URL=https://dbppf.bosscar.app
    ports:
      - "3003:3000"
    env_file: .env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always