FROM node:20-alpine
WORKDIR /app

ARG NEXT_PUBLIC_POCKETBASE_URL=http://127.0.0.1:8091

COPY package*.json ./
RUN npm install
COPY . .
RUN NEXT_PUBLIC_POCKETBASE_URL=${NEXT_PUBLIC_POCKETBASE_URL} npm run build
EXPOSE 3000
CMD ["npm", "start"]